### ISSUE TITLE
register a gradle plugin for pekko grpc

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-grpc#113]
Our equivalent of https://plugins.gradle.org/plugin/com.lightbend.akka.grpc.gradle

@raboof seems to be the owner of the Akka one - maybe Arnout can help us work out what we need to do

We need to fix up the paradox docs to match whatever we end up with Gradle plugin wise.

**Comment by mdedetrich** [comment]
I remember discussing this with you @pjfanning and I am under the impression that we are not allowed to publish the pekko-grpc gradle plugin into Gradles plugin repository because its against ASF policy.

Instead we need to publish the jars into ASF's nexus release repo, just like we do with sbt plugins or any other project.

**Comment by pjfanning** [comment]
@mdedetrich whatever we end up with, we need to fix the paradox docs to reflect the right approach - they current say we have a Gradle plugin at the standard Gradle repo.

**Comment by mdedetrich** [comment]
Agreed, this may end up taking some time/being annoying as we have to document how to publish via (i.e. doing `publishSigned` in gradle etc etc). Same deal goes with maven

**Comment by mdedetrich** [comment]
Okay so regarding whether we can publish our Gradle plugin to Gradles own Plugin repository versus our ASF nexus the only thing I could find is

> Where possible use platforms officially supported by Infra.

From https://incubator.apache.org/guides/distribution.html (under Release Platforms).

**Comment by mdedetrich** [comment]
Just got news from `#asfinfra` that they have a relationship with Gradle for publishing plugins, just need to make a ticket to help set it up.

**Comment by mdedetrich** [comment]
INFRA ticket created https://issues.apache.org/jira/browse/INFRA-24804

**Comment by pjfanning** [comment]
@mdedetrich you can take this and if you run into issues or don't have time, we can review again. I can look at the other open issues.
