### ISSUE TITLE
Publish the pekko-grpc-codegen package for Scala 2.13

### ISSUE THREAD

**Issue by brendo-m** [apache/incubator-pekko-grpc#180]
Can we have the codegen package published for 2.13 as well as 2.12 please? akka-grpc-codegen is published for 2.13 (albeit in a roundabout way) and this is a blocker for migrating to pekko-grpc for non-sbt build tools, e.g. for mill and in our case bazel.

More context:
* https://github.com/akka/akka-grpc/issues/949
* https://github.com/akka/akka-grpc/issues/1400

Thanks!

**Comment by pjfanning** [comment]
New snapshot jars including ones for Scala 2.13 and Scala 3 have been published. See https://repository.apache.org/content/groups/snapshots/org/apache/pekko/

We may release a v1.0.1 in the next few weeks. No firm plans yet.
