### ISSUE TITLE
reintroduce dependency on akka-http-cors (or pekko equivalent) 

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-grpc#22]
This project has a dependency on akka-http-cors. I have opened https://github.com/lomigmegard/akka-http-cors/issues/258

I have the code updated to use Pekko in a temp fork. As a workaround, I can inline that code in this repo. When issue 258 is addressed, we can use that instead. This is better because we won't have to update our license to mention the inlined code.

**Comment by mdedetrich** [comment]
So a cors release has been made against pekko, see https://github.com/lomigmegard/akka-http-cors/issues/258#issuecomment-1454762806

**Comment by mdedetrich** [comment]
@pjfanning Just letting you know that I am working on this now
