### ISSUE TITLE
add new compatibility test

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-grpc#228]
https://github.com/apache/incubator-pekko-grpc/tree/1.0.x/sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins

this test doesn't work with newer versions of protobuf - see https://github.com/protocolbuffers/protobuf-javascript/issues/127

the idea is to remove it to allow us to proceed with io.grpc and protobuf upgrades

this issue is about replacing it

**Comment by raboof** [comment]
switched to go
