### ISSUE TITLE
update docs to remove Akka/Lightbend refs

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-grpc#26]
* see also #25 
* need to fix up the URLs specified for the doc links (which are currently based on doc.akka.io but need to change to pekko.apache.org

**Comment by pjfanning** [comment]
largely done in https://github.com/apache/incubator-pekko-grpc/pull/57

**Comment by mdedetrich** [comment]
> largely done in #57

@pjfanning Can we close this? The PR you linked is already merged
