### ISSUE TITLE
Where do we publish the gradle plugin?

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko-grpc#40]
So afaik (and from some basic googling) Gradle Plugins are typically published to Gradle's official plugin repository (called plugin portal). Unlike with sbt plugins, it appears to be expected to publish plugins into their plugin portal because otherwise you have to manually add plugin repositories (see https://docs.gradle.org/current/userguide/plugins.html#sec:custom_plugin_repositories), this is even the case for releases (not just snapshots). Note that Lightbend published the plugin into Gradle's plugin portal.

So the question is from an ASF policy perspective are we allowed to publish into Gradle's plugin portal or do we have to publish it into Apache's maven repository.

**Comment by pjfanning** [comment]
https://plugins.gradle.org/search?term=org.apache appears to show that no ASF projects publish directly to the official plugin repo.

I think we should just document what users need to put in their gradle files - including the 'custom' gradle repo.

**Comment by mdedetrich** [comment]
If thats the case then we need to figure out how to make gradle publish gradle plugins to a non standard repo

**Comment by pjfanning** [comment]
I don't know but I assume that this is not much different from sbt plugins. You publish to Nexus and users can add a 'repository' definition to their Gradle script.

**Comment by pjfanning** [comment]
<img width="493" alt="image" src="https://user-images.githubusercontent.com/11783444/222420919-87e4f50d-541b-4c12-8a67-5a6874a27fec.png">

See how in the Gradle doc you linked to in the description, you can include maven repo details. With production releases of pekko-grpc, mavenCentral() will do. With pekko-grpc snapshots, users will need to link to https://repository.apache.org/content/groups/snapshots/ .

**Comment by mdedetrich** [comment]
Cool, can look into it after https://github.com/apache/incubator-pekko-grpc/pull/41 is merged

**Comment by mdedetrich** [comment]
I will merge this, we are forced to publish Gradle plugin in Apache's maven repo due to ASF policy
