### ISSUE TITLE
licenses: check for code that is copied from external projects

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-grpc#48]
* needs to be acknowledged in our license and/or notice

**Comment by mdedetrich** [comment]
@pjfanning Is this still valid?

**Comment by pjfanning** [comment]
found https://github.com/apache/incubator-pekko-grpc/blob/11e6f15b1e9edf425c8edb16c50b70e892f8b54b/runtime/src/main/scala/org/apache/pekko/grpc/internal/NettyClientUtils.scala#L192 -- but this looks like just a link to show how the netty method works - that there is no copied code

**Comment by pjfanning** [comment]
also https://github.com/apache/incubator-pekko-grpc/blob/11e6f15b1e9edf425c8edb16c50b70e892f8b54b/interop-tests/README.md?plain=1#L14C157-L14C230

This one needs investigation. grpc code is Apache licensed but if we find any code that is copied then we'll need to check source headers as well as update the repo LICENSE and NOTICE.

**Comment by pjfanning** [comment]
> found
> 
> https://github.com/apache/incubator-pekko-grpc/blob/11e6f15b1e9edf425c8edb16c50b70e892f8b54b/runtime/src/main/scala/org/apache/pekko/grpc/internal/NettyClientUtils.scala#L192
> 
> -- but this looks like just a link to show how the netty method works - that there is no copied code

I double checked and this is just a link to show how the Netty class works.
