### ISSUE TITLE
sbt publish job broken after scala3 merge

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-grpc#77]
see https://github.com/apache/incubator-pekko-grpc/actions/runs/5100731826/jobs/9169230377

I reran the job and it failed again (same way)

```
(plugin-tester-java / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
```

**Comment by pjfanning** [comment]
fyi @mdedetrich

**Comment by pjfanning** [comment]
@mdedetrich would it make sense to disable javadoc/scaladoc for 'plugin-tester-java' -- these API docs are probably not that useful

**Comment by mdedetrich** [comment]
@pjfanning It shouldn't even run, see https://github.com/apache/incubator-pekko-grpc/blob/f43a3a02998f26ca16b6d5e311f1378ad330810f/build.sbt#L271

**Comment by mdedetrich** [comment]
Solved via https://github.com/apache/incubator-pekko-grpc/actions/runs/5100950279/jobs/9169522744
