### ISSUE TITLE
Add github tag protection rules after release candidate

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko-grpc#85]
iirc This is one of the pekko modules that actually needs a git tag to function (hence why the `v0.0.0` tag already exists). Due to this we cannot add git tag protection rules now because we would be unable to delete the `v0.0.0` tag).

Instead after the first release candidate is made and a git tag for that release candidate is pushed, we can then delete the `v0.0.0` git tag and then add git tag protection rules.

**Comment by mdedetrich** [comment]
@pjfanning Given that the core reason why we needed a `v0.0.0` git tag is because the project initially was deriving versions directly from git, an issue that was fixed in https://github.com/apache/incubator-pekko-grpc/pull/145 are you okay with me deleting the `v0.0.0` git tag?

**Comment by pjfanning** [comment]
Is it possible to remove the tag without disturbing INFRA?

**Comment by mdedetrich** [comment]
No, thats the point of the git tag. This is why it makes sense to delete the `v0.0.0` git tag now before adding in the git tag protection rules.

**Comment by pjfanning** [comment]
That's my point - remove the tag yourself - I just don't like disturbing the INFRA team for this kind of thing. I'd prefer to leave the tag in place if we are unable to delete it ourselves. And in theory, we should be able to delete the tag ourselves.

**Comment by mdedetrich** [comment]
Yup I was just notifying you that this was my plan so you were aware, will do this today.
